site_name: lgbfscotland
site_url: https://github.com/jsleight1/lgbfscotland

nav:
  - Introduction: index.md
  - Reference: reference/SUMMARY.md

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/generate_reference.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy

theme:
  name: mkdocs