on:
  push:
    branches: [development]
  release:
    types: [published]
  workflow_dispatch:

name: Deploy documentation

permissions: read-all

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.os}} ${{matrix.config.python}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, python: '3.14'}
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.config.python }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build site
        run: uv run mkdocs build

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: site